//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sprint4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public int ID_Evento { get; set; }
        public string Nombre { get; set; }
        public string Salon { get; set; }
        public string Capacidad { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
