//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sprint4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int ID_Reserva { get; set; }
        public Nullable<System.DateTime> Fecha_De { get; set; }
        public Nullable<System.DateTime> Fecha_Hasta { get; set; }
        public string Cliente { get; set; }
        public string Recepcionista { get; set; }
        public string Habitacion { get; set; }
    }
}
